### ISSUE TITLE
About rgb565 Mode

### ISSUE THREAD

**Issue by JT365** [chuanjinpang/win10_idd_xfz1986_usb_graphic_driver_display#1]
rgb565模式的时候，是通过cpu进行字节拼接然后发给下位机的。请问创建DXGI monitor的时候，能够直接生成一个rgb565的surface吗？如果可以的话，那么CPU不需要做任何转换，可以把frame数据复制到用户空间然后直接发送给下位机。

**Comment by chuanjinpang** [comment]
没记错的话，好像不可以直接创建RGB565的surface, MS似乎是只有32bit true color模块，毕竟这个565太小众了。
